// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'disable_user_event': string;
  'ellipsis': string;
  'inline': string;
  'scrollable': string;
  'width_limiter': string;
}
export const cssExports: CssExports;
export default cssExports;
