// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    ant_danger_color: string;
    block: string;
    disable_user_event: string;
    ellipsis: string;
    inline: string;
    link: string;
    link_reverse: string;
    scrollable: string;
    user_active: string;
    width_limiter: string;
}
export const cssExports: CssExports;
export default cssExports;
